"""surface type en el overlay del lago

Revision ID: 405e85a697c4
Revises: 4416c554d599
Create Date: 2026-09-07 23:03:21.423338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405e85a697c4'
down_revision = '4416c554d599'
branch_labels = None
depends_on = None


def upgrade():
    # La columna es NOT NULL y la tabla puede tener polígonos ya sembrados, así
    # que entra con server_default para poder rellenarlos; el default se retira
    # al final para que el esquema quede igual que el modelo.
    with op.batch_alter_table('lake_geometries', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'surface_type', sa.String(length=10),
            nullable=False, server_default='water',
        ))

    # Reparación puntual de las filas anteriores a la columna: todo era "lago",
    # así que agua es el default correcto y solo hay que rescatar las islas.
    #
    # Sí, esto mira el nombre — que es justo lo que la columna viene a evitar.
    # La diferencia es que aquí se hace UNA vez sobre datos que ya existen, no
    # en cada petición: a partir de ahora quien crea el polígono declara su
    # superficie y `create_lake_geometry` rechaza cualquier otro valor.
    op.execute("""
        UPDATE lake_geometries
           SET surface_type = 'land'
         WHERE tenochtitlan_name IN ('Tenochtitlan', 'Tlatelolco')
            OR name ILIKE '%island%'
    """)

    with op.batch_alter_table('lake_geometries', schema=None) as batch_op:
        batch_op.alter_column('surface_type', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lake_geometries', schema=None) as batch_op:
        batch_op.drop_column('surface_type')

    # ### end Alembic commands ###
