"""sprint 1.5 unlock saved history stops

Revision ID: 4416c554d599
Revises: 26d19c20d530
Create Date: 2026-09-07 21:37:05.217545

Esta migración cambia el modelo de negocio: se pasa de suscripción por niveles
a un desbloqueo único. Eso significa tirar `subscriptions`, `payments` y la
columna `subscription_tier`, y ahí es donde autogenerate se queda corto: si se
aplica tal cual, cualquier usuario que ya hubiera pagado se queda sin acceso y
cualquier tour ya montado se queda sin paradas. Por eso el archivo lleva a mano
tres cosas que Alembic no puede adivinar:

  1. `users.has_full_access` es NOT NULL: se crea con server_default para que la
     tabla existente pueda rellenarse, y el default se quita al final.
  2. Se traspasa el acceso de quien ya tenía suscripción ANTES de tirar las
     tablas viejas — de ahí que los drop_table estén al final y no al principio.
  3. Las filas de `tour_places` se copian a `tour_stops` conservando su orden.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4416c554d599'
down_revision = '26d19c20d530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_purchase_provider_ref')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_user_id'), ['user_id'], unique=False)

    op.create_table('saved_places',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'place_id', name='uq_saved_place')
    )
    with op.batch_alter_table('saved_places', schema=None) as batch_op:
        batch_op.create_index('ix_saved_places_user', ['user_id', 'created_at'], unique=False)

    op.create_table('tour_stops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tour_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transition_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour_id', 'place_id', name='uq_tour_stop_place'),
    sa.UniqueConstraint('tour_id', 'position', name='uq_tour_stop_position')
    )
    op.create_table('content_reads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['historical_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_content_read')
    )
    with op.batch_alter_table('content_reads', schema=None) as batch_op:
        batch_op.create_index('ix_content_reads_user', ['user_id'], unique=False)

    with op.batch_alter_table('historical_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeline_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reading_time_minutes', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_historical_content_timeline_id'), ['timeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_content_topic'), ['topic'], unique=False)
        # Con nombre explícito: autogenerate lo dejaba en None y el downgrade
        # correspondiente (drop_constraint(None, ...)) revienta en PostgreSQL.
        batch_op.create_foreign_key(
            'fk_historical_content_timeline_id', 'timelines', ['timeline_id'], ['id']
        )
        batch_op.drop_column('required_subscription')

    with op.batch_alter_table('lake_geometries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lake_geometries_year_estimate'), ['year_estimate'], unique=False)

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('curation', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('editorial_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('why_visit', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('how_to_get_there', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visit_duration_text', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('entry_fee_mxn', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('entry_fee_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('entry_fee_text', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_free_entry', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_outdoor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('content_verified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_places_curation'), ['curation'], unique=False)
        batch_op.drop_column('average_rating')
        batch_op.drop_column('unlock_price')
        batch_op.drop_column('rating_count')
        batch_op.drop_column('entry_fee')
        batch_op.drop_column('required_subscription')

    with op.batch_alter_table('timelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('tour_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stop_index', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_tour_progress', ['tour_id', 'user_id'])
        # `current_place_index` se tira más abajo, después de copiar su valor:
        # si se dropea aquí, quien iba por la parada 3 vuelve al principio.

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_text', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('has_entry_fees', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('editorial_rating', sa.Float(), nullable=True))
        batch_op.drop_column('price')
        batch_op.drop_column('average_rating')
        batch_op.drop_column('includes_audio')
        batch_op.drop_column('required_subscription')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_locale', sa.String(length=5), nullable=True))
        # server_default obligatorio: la columna es NOT NULL y la tabla puede
        # tener filas. Sin él, PostgreSQL aborta con "column contains null
        # values" en cuanto haya un solo usuario registrado.
        batch_op.add_column(sa.Column(
            'has_full_access', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ))
        batch_op.add_column(sa.Column('full_access_since', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column(
            'total_places_visited', sa.Integer(), server_default='0', nullable=True
        ))

    # ------------------------------------------------------------------
    # traspaso de datos (antes de tirar nada)
    # ------------------------------------------------------------------

    # Quien ya había pagado conserva el acceso. La fecha se toma de la
    # suscripción si existe; si no, del alta de la cuenta.
    op.execute("""
        UPDATE users u
           SET has_full_access = true,
               full_access_since = COALESCE(
                   (SELECT s.started_at FROM subscriptions s
                     WHERE s.user_id = u.id ORDER BY s.started_at LIMIT 1),
                   u.subscription_start_date,
                   u.created_at,
                   now()
               )
         WHERE COALESCE(u.subscription_tier, 'free') <> 'free'
            OR EXISTS (SELECT 1 FROM subscriptions s
                        WHERE s.user_id = u.id AND s.is_active = true)
    """)

    # El avance dentro del tour se conserva: es el mismo número, solo cambia
    # de nombre al pasar de "sitio" a "parada".
    op.execute("""
        UPDATE tour_progress
           SET current_stop_index = COALESCE(current_place_index, 0)
    """)

    # Las paradas de los tours ya montados: `tour_places` solo guardaba la
    # pareja y un `order`. El audio y el texto de transición quedan a NULL
    # porque ese contenido todavía no existía.
    #
    # La posición se renumera con ROW_NUMBER en lugar de copiar `order` tal
    # cual: esa columna era nullable y sin restricción de unicidad, así que
    # perfectamente puede traer NULLs o empates que romperían el
    # UniqueConstraint(tour_id, position) de la tabla nueva.
    op.execute("""
        INSERT INTO tour_stops (id, tour_id, place_id, position, created_at)
        SELECT gen_random_uuid()::text,
               tp.tour_id,
               tp.place_id,
               (ROW_NUMBER() OVER (
                    PARTITION BY tp.tour_id
                    ORDER BY tp."order" NULLS LAST, tp.place_id
               ) - 1)::int,
               now()
          FROM tour_places tp
    """)

    # ------------------------------------------------------------------
    # y ahora sí, fuera lo viejo
    # ------------------------------------------------------------------
    op.drop_table('tour_places')
    op.drop_table('subscriptions')
    op.drop_table('payments')

    with op.batch_alter_table('tour_progress', schema=None) as batch_op:
        batch_op.drop_column('current_place_index')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_end_date')
        batch_op.drop_column('subscription_tier')
        batch_op.drop_column('subscription_start_date')
        # El default de servidor era el andamio del backfill: el modelo ya pone
        # False desde Python, así que el esquema queda igual que el modelo.
        batch_op.alter_column('has_full_access', server_default=None)
        batch_op.alter_column('total_places_visited', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_places_visited')
        batch_op.drop_column('full_access_since')
        batch_op.drop_column('has_full_access')
        batch_op.drop_column('preferred_locale')

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_subscription', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('includes_audio', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('editorial_rating')
        batch_op.drop_column('has_entry_fees')
        batch_op.drop_column('duration_text')

    with op.batch_alter_table('tour_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_place_index', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_tour_progress', type_='unique')
        batch_op.drop_column('current_stop_index')

    with op.batch_alter_table('timelines', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_subscription', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entry_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unlock_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_places_curation'))
        batch_op.drop_column('content_verified_at')
        batch_op.drop_column('is_outdoor')
        batch_op.drop_column('is_free_entry')
        batch_op.drop_column('entry_fee_text')
        batch_op.drop_column('entry_fee_usd')
        batch_op.drop_column('entry_fee_mxn')
        batch_op.drop_column('visit_duration_text')
        batch_op.drop_column('how_to_get_there')
        batch_op.drop_column('why_visit')
        batch_op.drop_column('editorial_rating')
        batch_op.drop_column('curation')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('tagline')

    with op.batch_alter_table('lake_geometries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lake_geometries_year_estimate'))

    with op.batch_alter_table('historical_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_subscription', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_historical_content_timeline_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_historical_content_topic'))
        batch_op.drop_index(batch_op.f('ix_historical_content_timeline_id'))
        batch_op.drop_column('reading_time_minutes')
        batch_op.drop_column('topic')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('timeline_id')

    op.create_table('tour_places',
    sa.Column('tour_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('place_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('tour_places_place_id_fkey')),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name=op.f('tour_places_tour_id_fkey')),
    sa.PrimaryKeyConstraint('tour_id', 'place_id', name=op.f('tour_places_pkey'))
    )
    op.create_table('payments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refund_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('refund_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refunded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tier', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('monthly_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('subscriptions_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('content_reads', schema=None) as batch_op:
        batch_op.drop_index('ix_content_reads_user')

    op.drop_table('content_reads')
    op.drop_table('tour_stops')
    with op.batch_alter_table('saved_places', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_places_user')

    op.drop_table('saved_places')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_user_id'))

    op.drop_table('purchases')
    # ### end Alembic commands ###
